package:
  format-version: "1.0.0"
  name: "smartenergy_metrology"
  version: "v1.1.0"
  type: "api"
  status: "production"
  required: false

  dependencies:
    - name: "core"
      type: "package"
      version: "v3.15.3"
    - name: "csp"
      type: "package"
      version: "v3.22.5"
